name: hivez_flutter
description: "A library for using Hivez with Flutter. Includes Hivez and Hive CE Flutter bindings."
version: 1.2.0+1
homepage: https://github.com/jozzdart/hivez
repository: https://github.com/jozztech/hivez/tree/main/hivez_flutter
issue_tracker: https://github.com/jozzdart/hivez/issues
topics:
  - hive
  - database
  - nosql
  - clean
  - hivez

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive_ce_flutter: ^2.3.2
  hivez: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
