name: hivez
description: "The cleanest dart database. Blazingly fast queries, easy, type-safe, boilerplate-free. Heavily tested, production-ready. (Wrapping hive_ce with x1000 faster queries)"
version: 1.1.0
homepage: https://github.com/jozzdart/hivez
repository: https://github.com/jozzdart/hivez/tree/main/hivez
issue_tracker: https://github.com/jozzdart/hivez/issues
topics:
  - hive
  - database
  - nosql
  - clean
  - queries

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  hive_ce: ^2.11.3
  meta: ^1.16.0
  shrink: ^1.5.12
  synchronized: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  mocktail: ^1.0.4
  hive_ce_flutter: ^2.3.2
